### ISSUE TITLE
Crash on linux with wayland.

### ISSUE THREAD

**Issue by ZeyadMoustafaKamal** [Inlyne-Project/inlyne#368]
After I have installed it in my archlinux with wayland I am not able to run it.  It just crashes.

```
libEGL warning: egl: failed to create dri2 screen
libEGL warning: egl: failed to create dri2 screen
wp_linux_drm_syncobj_manager_v1#49: error 0: Surface already has a syncobj attached
Protocol error 0 on object wp_linux_drm_syncobj_manager_v1@49: 
panicked at /home/zeyad/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs:734:18:
Error in Surface::configure: Validation Error

Caused by:
    Requested present mode Fifo is not in the list of supported present modes: []

Well, this is embarrassing.

inlyne had a problem and crashed. To help us diagnose the problem you can send us a crash report.
We have generated a report file at "/tmp/inlyne-report-3802833d3cd7e35b.md". You can search
for issues with similar explanations at the following url:

- https://github.com/Inlyne-Project/inlyne/issues?q=label%3AC-crash-report

and you can submit a new crash report using the report file as a template if there are no existing
issues matching your own (the following link has the crash report label)

- https://github.com/Inlyne-Project/inlyne/issues/new?labels=C-crash-report

We take privacy seriously, and do not preform any auotmated error collection. In order to improve
the software we, rely on people to submit reports.

Thank you kindly!warning: queue 0x64841d5daf30 destroyed while proxies still attached:
  xdg_wm_base#23 still attached
  wl_output#15 still attached
  xdg_activation_v1#14 still attached
  zwp_pointer_constraints_v1#13 still attached
  zwp_text_input_manager_v3#12 still attached
  zxdg_decoration_manager_v1#11 still attached
  zwp_relative_pointer_manager_v1#10 still attached
  wp_fractional_scale_manager_v1#9 still attached
  wp_viewporter#8 still attached
  wl_shm#7 still attached
  wl_subcompositor#6 still attached
  wl_compositor#5 still attached
  wl_seat#4 still attached
  wl_registry#2 still attached
  ```
# Crash Report

| Name | `inlyne` |
| ---: | :--- |
| Version | `0.4.1` |
| Operating System | Arch Linux Rolling Release [64-bit] |

`````text
Cause: Error in Surface::configure: Validation Error

Caused by:
    Requested present mode Fifo is not in the list of supported present modes: []


Explanation:
Panic occurred in file '/home/zeyad/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.16.3/src/backend/direct.rs' at line 734
`````

<details>
<summary>(backtrace)</summary>

`````text
   0: 0x648418422aa9 - <unresolved>
   1: 0x6484184264c3 - <unresolved>
   2: 0x648418433e33 - <unresolved>
   3: 0x64841837cbd1 - <unresolved>
   4: 0x648417948050 - <unresolved>
   5: 0x6484179fb8b2 - <unresolved>
   6: 0x648417a02b6c - <unresolved>
   7: 0x64841793702a - <unresolved>
   8: 0x64841794bbd3 - <unresolved>
   9: 0x648417a117b3 - <unresolved>
  10: 0x6484179f09ed - <unresolved>
  11: 0x648418784630 - <unresolved>
  12: 0x64841794bff5 - <unresolved>
  13: 0x7494ca906e08 - <unresolved>
  14: 0x7494ca906ecc - __libc_start_main
  15: 0x6484178efc25 - <unresolved>
  16:        0x0 - <unresolved>
`````

</details>

---

Also I have tried to install it using `cargo` and tried building it from the source and I am getting the same problem. I have AMD GPU and NVIDIA RTX 3060 GPU.

#### Some additional info you might need

the output of `uname -a` 
`Linux arch 6.6.58-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 23 Oct 2024 17:28:15 +0000 x86_64 GNU/Linux`

the output of `lspci | grep VGA` 
`05:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cezanne [Radeon Vega Series / Radeon Vega Mobile Series] (rev c5)`

Also this could be related to AMD.  As when I run it using `prime-run` I am getting another problem. 

```
panicked at /home/zeyad/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.2/src/gles/egl.rs:304:14:
called `Result::unwrap()` on an `Err` value: BadDisplay
Well, this is embarrassing.

inlyne had a problem and crashed. To help us diagnose the problem you can send us a crash report.
We have generated a report file at "/tmp/inlyne-report-60dcacea1f13fbe3.md". You can search
for issues with similar explanations at the following url:

- https://github.com/Inlyne-Project/inlyne/issues?q=label%3AC-crash-report

and you can submit a new crash report using the report file as a template if there are no existing
issues matching your own (the following link has the crash report label)

- https://github.com/Inlyne-Project/inlyne/issues/new?labels=C-crash-report

We take privacy seriously, and do not preform any auotmated error collection. In order to improve
the software we, rely on people to submit reports.

Thank you kindly!warning: queue 0x59c4a3709f30 destroyed while proxies still attached:
  xdg_wm_base#23 still attached
  wl_output#15 still attached
  xdg_activation_v1#14 still attached
  zwp_pointer_constraints_v1#13 still attached
  zwp_text_input_manager_v3#12 still attached
  zxdg_decoration_manager_v1#11 still attached
  zwp_relative_pointer_manager_v1#10 still attached
  wp_fractional_scale_manager_v1#9 still attached
  wp_viewporter#8 still attached
  wl_shm#7 still attached
  wl_subcompositor#6 still attached
  wl_compositor#5 still attached
  wl_seat#4 still attached
  wl_registry#2 still attached

``` 

# Crash Report

| Name | `inlyne` |
| ---: | :--- |
| Version | `0.4.1` |
| Operating System | Arch Linux Rolling Release [64-bit] |

`````text
Cause: called `Result::unwrap()` on an `Err` value: BadDisplay

Explanation:
Panic occurred in file '/home/zeyad/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.16.2/src/gles/egl.rs' at line 304
`````

<details>
<summary>(backtrace)</summary>

`````text
   0: 0x59c4764f17a6 - <unresolved>
   1: 0x59c47712e150 - <unresolved>
   2: 0x59c4770b69ad - <unresolved>
   3: 0x59c476fe50d5 - <unresolved>
   4: 0x59c4770357b4 - <unresolved>
   5: 0x59c476f7d9ec - <unresolved>
   6: 0x59c4765463f7 - <unresolved>
   7: 0x59c47654d994 - <unresolved>
   8: 0x59c4766137b3 - <unresolved>
   9: 0x59c4765f29ed - <unresolved>
  10: 0x59c477386630 - <unresolved>
  11: 0x59c47654dff5 - <unresolved>
  12: 0x70d5b35d2e08 - <unresolved>
  13: 0x70d5b35d2ecc - __libc_start_main
  14: 0x59c4764f1c25 - <unresolved>
  15:        0x0 - <unresolved>
`````

</details>

---

**Comment by ZeyadMoustafaKamal** [comment]
I pulled the latest modification and built it again and it works with **just** and amd card i.e without `prime-run`. I think it could be because of d0b076c5a1adc8d8893c3c328ba7da75ae05b040. It seems from the other issues that this happened before like this #283 and the solution was also to update the deps. I think you can add a note in the README for other people to run `cargo update` if they have a problem with wayland on linux.

**Comment by CosmicHorrorDev** [comment]
Happy to hear it's working for you now! Sorry I didn't get around to digging into your issue earlier. Life has been busy 😅

**Comment by ZeyadMoustafaKamal** [comment]
@CosmicHorrorDev No worries. And thanks for your amazing project.
