### ISSUE TITLE
Add Wayland support

### ISSUE THREAD

**Issue by CRAG666** [Inlyne-Project/inlyne#55]
His project looks great, but I can't use it on Wayland

**Comment by trimental** [comment]
Wayland support should work automatically. I'm afraid I'll need more details before I can fix your specific issue.

**Comment by CRAG666** [comment]
@trimental 
![imagen](https://user-images.githubusercontent.com/34254373/204396828-47773c2b-5883-4601-878f-41e6ed24196f.png)
this is error

**Comment by LovecraftianHorror** [comment]
Poked into this for a bit. It looks like it's failing to setup the clipboard provider since Wayland takes some special care to be used in `copypasta`

I can work on resolving this is a week or so

**Comment by steven-omaha** [comment]
Still happening on latest `HEAD`, but with a different error message.

```
$ RUST_BACKTRACE=full cargo run --profile release-debug -- README.md 

     Running `target/release-debug/inlyne README.md`
thread 'main' panicked at src/main.rs:337:26:
called `Result::unwrap()` on an `Err` value: Renderer failed to redraw the screen

Caused by:
    0: Failed to acquire next swap chain texture
    1: The underlying surface has changed, and therefore the swap chain must be updated
stack backtrace:
   0:     0x5641f19957ac - std::backtrace_rs::backtrace::libunwind::trace::ha637c64ce894333a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x5641f19957ac - std::backtrace_rs::backtrace::trace_unsynchronized::h47f62dea28e0c88d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5641f19957ac - std::sys_common::backtrace::_print_fmt::h9eef0abe20ede486
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5641f19957ac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed7f999df88cc644
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5641f19c7e50 - core::fmt::rt::Argument::fmt::h1539a9308b8d058d
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/rt.rs:142:9
   5:     0x5641f19c7e50 - core::fmt::write::h3a39390d8560d9c9
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/fmt/mod.rs:1120:17
   6:     0x5641f1990ccf - std::io::Write::write_fmt::h5fc9997dfe05f882
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/io/mod.rs:1762:15
   7:     0x5641f1995594 - std::sys_common::backtrace::_print::h894006fb5c6f3d45
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x5641f1995594 - std::sys_common::backtrace::print::h23a2d212c6fff936
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x5641f1996e07 - std::panicking::default_hook::{{closure}}::h8a1d2ee00185001a
  10:     0x5641f1996b6f - std::panicking::default_hook::h6038f2eba384e475
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:292:9
  11:     0x5641f19972f8 - std::panicking::rust_panic_with_hook::h2b5517d590cab22e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:779:13
  12:     0x5641f19971de - std::panicking::begin_panic_handler::{{closure}}::h233112c06e0ef43e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:657:13
  13:     0x5641f1995c76 - std::sys_common::backtrace::__rust_end_short_backtrace::h6e893f24d7ebbff8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x5641f1996f42 - rust_begin_unwind
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
  15:     0x5641f19c4ee5 - core::panicking::panic_fmt::hbf0e066aabfa482c
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
  16:     0x5641f19c5423 - core::result::unwrap_failed::hddb4fea594200c52
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
  17:     0x5641f0afd237 - core::result::Result<T,E>::unwrap::h0c609f98b78e300a
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1077:23
  18:     0x5641f0afd237 - inlyne::Inlyne::run::{{closure}}::hb30eaaac8e3f5f6d
                               at /home/xxxxxxxx/tmp/inlyne/src/main.rs:334:21
  19:     0x5641f0af80c1 - winit::platform_impl::platform::sticky_exit_callback::h23b6b0ebacdb73e3
                               at /home/xxxxxxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/mod.rs:884:9
  20:     0x5641f0af80c1 - winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration::h46b41a27e6030504
                               at /home/xxxxxxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:375:21
  21:     0x5641f0af883d - winit::platform_impl::platform::x11::EventLoop<T>::run_return::h72d7bd20c671de32
                               at /home/xxxxxxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:483:27
  22:     0x5641f0af883d - winit::platform_impl::platform::x11::EventLoop<T>::run::h115ee88106035186
                               at /home/xxxxxxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/x11/mod.rs:498:25
  23:     0x5641f0b2295f - winit::platform_impl::platform::EventLoop<T>::run::hed97eb62ce832d8c
                               at /home/xxxxxxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/mod.rs:792:56
  24:     0x5641f0b2295f - winit::event_loop::EventLoop<T>::run::h126868f6a272c826
                               at /home/xxxxxxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/event_loop.rs:305:25
  25:     0x5641f0b2295f - inlyne::Inlyne::run::h1480f5fa644b3fde
                               at /home/xxxxxxxx/tmp/inlyne/src/main.rs:295:20
  26:     0x5641f0b2295f - inlyne::main::h43adb6420f63ca66
                               at /home/xxxxxxxx/tmp/inlyne/src/main.rs:779:5
  27:     0x5641f0b50f83 - core::ops::function::FnOnce::call_once::h45222108cbf51020
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:250:5
  28:     0x5641f0b50f83 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9e851b079dde0dc4
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/sys_common/backtrace.rs:154:18
  29:     0x5641f0b44a4d - std::rt::lang_start::{{closure}}::h60ca860b9b356aca
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:167:18
  30:     0x5641f198a037 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd95060ecd5e1ca24
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/ops/function.rs:284:13
  31:     0x5641f198a037 - std::panicking::try::do_call::h6e8cf51db32a6e4b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  32:     0x5641f198a037 - std::panicking::try::h3a52eefe24fe3c29
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  33:     0x5641f198a037 - std::panic::catch_unwind::h24c28c23c02c3841
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  34:     0x5641f198a037 - std::rt::lang_start_internal::{{closure}}::h705d3c9cbc06ef47
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:48
  35:     0x5641f198a037 - std::panicking::try::do_call::ha21f52ba13158470
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:552:40
  36:     0x5641f198a037 - std::panicking::try::h5581346bf6aeb1f8
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:516:19
  37:     0x5641f198a037 - std::panic::catch_unwind::h7919645a6b72e25b
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panic.rs:142:14
  38:     0x5641f198a037 - std::rt::lang_start_internal::h12de51168669836e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:148:20
  39:     0x5641f0b44a3e - std::rt::lang_start::he5f97c5580181d6e
                               at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/rt.rs:166:17
  40:     0x7fef09438cd0 - <unknown>
  41:     0x7fef09438d8a - __libc_start_main
  42:     0x5641f0a39f25 - _start
  43:                0x0 - <unknown>
```

**Comment by CosmicHorrorDev** [comment]
@steven-omaha current `main` has separate features for `x11` and `wayland`. I think you want `--no-default-features --features wayland` (from memory, so may be wrong)

Also thanks for using the profile that keeps debug info!

**Comment by steven-omaha** [comment]
@CosmicHorrorDev Thanks, didn't know that. In that case, I don't get a crash, but an exit with error code 1. 

```
$ cargo run --profile release-debug --no-default-features --features wayland -- README.md 
     Running `target/release-debug/inlyne README.md`
interface 'wl_surface' has no event 2
```

again on Hyprland

**Comment by CosmicHorrorDev** [comment]
@steven-omaha Looking at the logs it looks like it fails after requesting some image. Can you try running with a file that doesn't have any images to see if that's your issue?

**Comment by CosmicHorrorDev** [comment]
@steven-omaha can you check to see if the branch for #298 fixes your issue?

**Comment by steven-omaha** [comment]
@CosmicHorrorDev yes, that works!

**Comment by CosmicHorrorDev** [comment]
@steven-omaha #298 is now included in the latest release. I'm going to go ahead and close this as wayland support should _generally_ work (sans various issues that are still getting ironed out)
